### ISSUE TITLE
Is it normal that the function is failing on Netlify?

### ISSUE THREAD

**Issue by riccardogioratoatoms** [prisma/prisma2-e2e-tests-netlify-zisi#3]
Is it normal that the function is failing on Netlify?

![image](https://user-images.githubusercontent.com/61690514/84475319-a01ee680-ac8c-11ea-84d3-18ab2603a499.png)

**Comment by janpio** [comment]
This project was part of https://github.com/prisma/e2e-tests - which unfortunately was not documented here. Was it linked to somewhere else or did you find it by search?

As far as I can see, we replaced this test (and this repo and deployment) with better suited alternatives listed on https://github.com/prisma/e2e-tests/tree/master/platforms

Correct @divyenduz @Luca?

**Comment by riccardogioratoatoms** [comment]
I just googled "prisma2 e2e netlify" and this was the first result @janpio

**Comment by janpio** [comment]
Ok, then you are better off with the second link I included. We will clean this up.
